### ISSUE TITLE
Is it possible to run this on the command line

### ISSUE THREAD

**Issue by holyman2k** [Lorenzooone/FEHDataExtractor#1]
Hi, loved your extractor.  but if i want to extract all lz (all unit in person folder), is there a way to select list of files or have the app run on the command line?

**Comment by Lorenzooone** [comment]
You can select multiple files by doing the same stuff you usually do to select more files (drag to select, click on first -> shift + click on last or multiple ctrl+click) while choosing the file you want to extract.

**Comment by Lorenzooone** [comment]
Hope this helped! 
CLI would be really neat, but I'd like to implement more stuff and then, if the demand is high enough, make it work from cmd.

**Comment by holyman2k** [comment]
cool, that helps, thank you
