### ISSUE TITLE
Can't extract skill files

### ISSUE THREAD

**Issue by izumi-niche** [Lorenzooone/FEHDataExtractor#10]
As of the new FEH update, it's not possible to extract any of the files in assets/Common/SRPG/Skill, all of them giving the same error: "Arithmetic operation resulted in an overflow"
[error.txt](https://github.com/Lorenzooone/FEHDataExtractor/files/6434160/error.txt)

**Comment by Lorenzooone** [comment]
Could you please provide one of the files the issue happens for?
It would help speed up the debugging process a bunch.
Thanks!

**Comment by izumi-niche** [comment]
Yep!
https://www111.zippyshare.com/v/xRRBxYgs/file.html

**Comment by Lorenzooone** [comment]
Hmm... I'm getting a 403 when I try to access the file... Are you sure the link is correct?

**Comment by izumi-niche** [comment]
It works for me, but I can try uploading it to google drive instead.
https://drive.google.com/file/d/1lsRlDn-oUw2Fb5MCDoaR75sT3YYzAsAX/view?usp=sharing

**Comment by Lorenzooone** [comment]
Fixed! Many thanks for the bug report!
(Updated release is available)
