### ISSUE TITLE
Exception when extracting Person files

### ISSUE THREAD

**Issue by izumi-niche** [Lorenzooone/FEHDataExtractor#11]
After the Book 6 update trying to extract any Person files causes an exception.
[error.txt](https://github.com/Lorenzooone/FEHDataExtractor/files/7657772/error.txt)
[211201_embla.bin.lz](https://drive.google.com/file/d/1FB6bhganEaywMOnRmgaRMwNmyF1HhS4v/view)

**Comment by Lorenzooone** [comment]
Thanks!
Fixed in: https://github.com/Lorenzooone/FEHDataExtractor/releases/tag/3.4.14
