### ISSUE TITLE
Latest quest 822_legend16.bin.lz triggers an index out of bounds error

### ISSUE THREAD

**Issue by swablueme** [Lorenzooone/FEHDataExtractor#2]
Release 3.2.0 causes an index out of bounds error on a toString method on what is presumably the new quests
https://i.imgur.com/K7mQVKo.png

[822_legend16.bin.lz.zip](https://github.com/Lorenzooone/FEHDataExtractor/files/3119909/822_legend16.bin.lz.zip)

**Comment by Lorenzooone** [comment]
Added support for "Alliegence Battles" game mode string, that's what was making it crash. Fixed in the latest release.
