### ISSUE TITLE
(another) Index out of bounds of the array error

### ISSUE THREAD

**Issue by swablueme** [Lorenzooone/FEHDataExtractor#3]
Great apologies (I really enjoy using this program), it is triggered by using the quest options on the latest set of bride quests 
[84_bride03.bin.lz.zip](https://github.com/Lorenzooone/FEHDataExtractor/files/3201000/84_bride03.bin.lz.zip)

**Comment by Lorenzooone** [comment]
Yeah... These cannot be prevented unless I inserted something along the lines of "UNKNOWN GAMEMODE", which wouldn't be descriptive at all. Sorry!

**Comment by Lorenzooone** [comment]
(The issue itself has been fixed though)

**Comment by swablueme** [comment]
Thanks, I love your program :)
