### ISSUE TITLE
Issues regarding FEHDataExtractor

### ISSUE THREAD

**Issue by ghost** [Lorenzooone/FEHDataExtractor#4]
Hello! Sorry to be of any bother, but I've ran into some issues extracting the .bin.lz files from "assets/Common/Mission and "assets/Common/SRPG/Skill" as each attempt from every file within those folders fail, so I believe the encryption increased. This issue happened when Version 3.6.0 was released. Your help is truly appreciated. Thank you.

**Comment by Lorenzooone** [comment]
Thanks a lot for the report! I'll check the issue out after my college exam on Monday.
Could you please, in the meantime, give me a file from Mission and a file from Skill that are not working? (I'm lazy and don't want to update the game on PC because that would take a while)
Thanks!

**Comment by ghost** [comment]
Thanks for the reply. Here's the files i'm talking about, but by all means, take all the time you want. I wish you well on your exam.

**From Skill:**
- https://drive.google.com/open?id=1UigawSvudSrKU7xTLiosz9-7kcH7wZ9Y

**From Mission:**
- https://drive.google.com/open?id=1EDo48jXVzwCspNkrQWw3Tqcs0_hXSY1b

**Comment by Lorenzooone** [comment]
I tried the skill one and it worked fine... Were you using the latest release?

Anyhow, fixed the mission one. Let me know if Skills still have an issue for you with the latest release I'm uploading right now. Thanks!

**Comment by ghost** [comment]
Yes, I was using the absolute latest release before this issue occured, so I thought the latest file from Skill had issues, but it turned out I was wrong. Thank you very much for your generous assistance and have the rest of your lovely day!
