### ISSUE TITLE
Out of bounds error on the new halloween quests and duo unit

### ISSUE THREAD

**Issue by swablueme** [Lorenzooone/FEHDataExtractor#5]
I saw this on Discord which might help maybe:
![image](https://user-images.githubusercontent.com/10569495/66389953-4edf9880-ea15-11e9-8fc6-c048062a2fe7.png)
![image](https://user-images.githubusercontent.com/10569495/66390054-86e6db80-ea15-11e9-9dfd-5587fd3caacd.png)
The two trouble lzs are attached. Sorry for being trouble.
[MEmu Download.zip]
(https://github.com/Lorenzooone/FEHDataExtractor/files/3702021/MEmu.Download.zip)

**Comment by Lorenzooone** [comment]
Try this https://github.com/Lorenzooone/FEHDataExtractor/releases/tag/3.4.4
and tell me if it works and if the descriptions of the triggers and of the gamemode check the quests. (Don't have the localization data to check myself)

This update makes it so the next updates will be a lot less likely to make this crash.

**Comment by swablueme** [comment]
Thankyou so much lorenzoone for your hard work! Also that fixes the issue ^^ I have just tested it with .lz from both the quests and character.
