### ISSUE TITLE
Problem with Unit files.

### ISSUE THREAD

**Issue by MrGengarr** [Lorenzooone/FEHDataExtractor#7]
In the latest update (4.6.0) if you try to open the latest unit file "200601_kakusei" from SRPG/Person the tool gets a fatal error with the following details:

 at StringXor..ctor(Int64 a, Byte[] data, Byte[] A)
   at SinglePerson.InsertIn(Int64 a, Byte[] data)
   at ExtractionBase.InsertIn(HSDARC archive, Int64 a, Byte[] data)
   at BaseExtractArchive`1.InsertIn(Int64 a, Byte[] data)
   at ExtractionBase.InsertIn(HSDARC archive, Int64 a, Byte[] data)

Doing a stack case on the solution in Visual studio gave me the following:

![](https://cdn.discordapp.com/attachments/702043284955988078/718565521485987851/unknown.png)

Hope the information is useful.

**Comment by Lorenzooone** [comment]
Yeah, they changed the way they store dragonflowers for the units and that screwed the program over. 
Currently working on a fix!

**Comment by MrGengarr** [comment]
Hmm yeah I think I heard Hertz say it got changed from a single byte to a 32 bit value now, but I'm guessing the issue goes deeper than simply changing a variable type though.

**Comment by Lorenzooone** [comment]
Not only that, it also became a pointer and contains more data now than just the dragonflower number info.
Will have to research on what the information being stored is before pushig an update.

**Comment by Lorenzooone** [comment]
Fixed.

**Comment by swablueme** [comment]
Thankyou :)
