### ISSUE TITLE
Problem with Tempest Trials 

### ISSUE THREAD

**Issue by MrGengarr** [Lorenzooone/FEHDataExtractor#9]
New update seems to have changed the Tempest Trials file since the tool crashes when trying to get the txt file, probably has something to do with the new point system they introduced.

Picture of the call stack if its of any help:
![Capture](https://user-images.githubusercontent.com/52722650/111419406-a96b3280-86a6-11eb-90b2-a72eea0f601e.PNG)

**Comment by Lorenzooone** [comment]
Hello, could you please attach the .bin file that causes the crash? It would help expedite the fixing process a ton.
Thanks!

**Comment by MrGengarr** [comment]
Sure!
https://drive.google.com/file/d/1HVmxNDHv7puctDTYl3IOfSG-LvbxwJS-/view?usp=sharing

**Comment by Lorenzooone** [comment]
Fixed. https://github.com/Lorenzooone/FEHDataExtractor/releases/tag/3.4.12
Hope it helps, and thanks again for the bug report.
